version: '3.9'

services:
  web:
    build:
      context: .
    container_name: django 
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/app_data
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16.2
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - /usr/src/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}