# Generated by Django 4.2.11 on 2024-04-24 02:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_equipment_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='equipment',
            name='receipt_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата поступления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=255, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(default='01', max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stock', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='capacity',
            field=models.PositiveBigIntegerField(verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
