# Generated by Django 4.2.11 on 2024-04-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование оборудования'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование склада'),
        ),
    ]
